import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "fintech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className="text-foreground h-screen bg-[var(--background)]">
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
      </ThemeProvider>
        </body>
    </html>
  );
}
